apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-sever
  labels:
    app: config-sever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-sever
  template:
    metadata:
      labels:
        app: config-sever
    spec:
      containers:
        - name: config-sever
          image: lordbyron.azurecr.io/config-server:v1
          env:
            - name: GIT_URI
              valueFrom:
                secretKeyRef:
                  name: git-secret
                  key: git-uri
            - name: GIT_USER
              valueFrom:
                secretKeyRef:
                  name: git-secret
                  key: git-user
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-secret
                  key: git-token
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-sever
  ports:
    - protocol: TCP
      port: 8888
